### ISSUE TITLE
Training for a single machine with multiple GPUs

### ISSUE THREAD

**Issue by chenjiahao0124** [mahaoxiang822/Scale-Balanced-Grasp#10]
Hello, you have done a great job. May I ask how to set up training for a single machine with multiple GPUs? I encountered the following error while conducting multi GPU training and hope you can answer it. Thank
![Uploading Snipaste_2024-12-08_20-04-35.png…]()
 you.

**Comment by chenjiahao0124** [comment]
File "C:\Users\win10\.conda\envs\CJH\lib\site-packages\torch\nn\parallel\parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "C:\Users\win10\.conda\envs\CJH\lib\site-packages\torch\_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "C:\Users\win10\.conda\envs\CJH\lib\site-packages\torch\nn\parallel\parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "C:\Users\win10\.conda\envs\CJH\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\CJH\VL-Grasp-main\VL-Grasp-main\BalancedGrasp\models\graspnet.py", line 162, in forward
    end_points = self.grasp_generator(end_points)
  File "C:\Users\win10\.conda\envs\CJH\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\CJH\VL-Grasp-main\VL-Grasp-main\BalancedGrasp\models\graspnet.py", line 107, in forward
    grasp_top_views_rot, _, _, _, end_points = match_grasp_view_and_label(end_points)
  File "D:\CJH\VL-Grasp-main\VL-Grasp-main\BalancedGrasp\utils\label_generation.py", line 142, in match_grasp_view_and_label
    top_template_views_rot = torch.gather(template_views_rot, 2, top_view_inds_).squeeze(2)
RuntimeError: Size does not match at dimension 3 expected index [1, 1024, 1, 3, 3] to be smaller than src [1, 1024, 300, 1, 3] apart from dimension 2

**Comment by Ldj-2004** [comment]
Hi,I've met the same problems as yours. Have you solved yet? @chenjiahao0124
